# Generated by Django 5.0.7 on 2024-07-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='json_files/'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
